<a href="https://colab.research.google.com/github/andrecarlos26/Projeto-Interdisciplinar-SI-2/blob/main/Pr%C3%A9_processamento_e_Tratamento_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import statistics as sts
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder


caminho = '/content/drive/My Drive/microdados_enem_2019/MICRODADOS_ENEM_2019_PE.csv'
dados_pe = pd.read_csv(caminho)

In [ ]:
dados_pe.head()

NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA  ... Q023  Q024 Q025
0  190001044305    2019                  2610004  ...    A     C    B
1  190001051159    2019                  2604007  ...    A     A    A
2  190001058610    2019                  2614105  ...    A     B    B
3  190001070444    2019                  2610509  ...    B     E    B
4  190001087987    2019                  2610707  ...    A     A    A

[5 rows x 136 columns]

In [ ]:
# Encontrar index da feature
dados_pe.columns.get_loc('NU_NOTA_REDACAO')

110

**Substituição dos valores nulos pela mediana**

In [ ]:
# Criação e inicio de tratamento 
# Nota em Matematica
mediana = dados_pe['NU_NOTA_MT'].median()
dados_pe['NU_NOTA_MT'].fillna(mediana, inplace=True)

In [ ]:
# Ciencias da natureza
mediana = dados_pe['NU_NOTA_CN'].median()
dados_pe['NU_NOTA_CN'].fillna(mediana, inplace=True)

In [ ]:
# Ciencias Humanas
mediana = dados_pe['NU_NOTA_CH'].median()
dados_pe['NU_NOTA_CH'].fillna(mediana, inplace=True)

In [ ]:
# Linguagens e seus códigos
mediana = dados_pe['NU_NOTA_LC'].median()
dados_pe['NU_NOTA_LC'].fillna(mediana, inplace=True)

In [ ]:
mediana = dados_pe['NU_NOTA_REDACAO'].median()
dados_pe['NU_NOTA_REDACAO'].fillna(mediana, inplace=True)

**Criação da coluna Média**

In [ ]:
notas = dados_pe.iloc[:,  np.r_[91:95,110]].values
notas

array([[619.6, 674.7, 629.1, 705.7, 880. ],
       [462.2, 499.7, 519.3, 496. , 580. ],
       [462.2, 499.7, 519.3, 496. , 580. ],
       ...,
       [519.4, 513.3, 569.3, 508.5, 700. ],
       [403. , 538.7, 533.9, 395.2, 560. ],
       [499.9, 580.5, 547.5, 478.2, 880. ]])

In [ ]:
media = []

for i in notas:
  media.append(sts.mean(i))
media

[701.82,
 511.44,
 511.44,
 511.44,
 511.44,
 437.34000000000003,
 511.44,
 655.6,
 511.44,
 526.34,
 511.44,
 477.54,
 651.76,
 634.92,
 511.44,
 511.44,
 539.9,
 551.5,
 511.44,
 587.12,
 494.44,
 531.6,
 678.0600000000001,
 526.52,
 600.04,
 596.04,
 641.08,
 511.44,
 504.22,
 675.38,
 582.48,
 688.9,
 687.58,
 517.56,
 642.74,
 616.28,
 580.96,
 427.98,
 469.78000000000003,
 511.44,
 612.5,
 448.42,
 632.14,
 585.4,
 600.14,
 511.44,
 511.44,
 556.22,
 511.44,
 511.44,
 537.6600000000001,
 520.06,
 532.16,
 528.5799999999999,
 440.98,
 576.24,
 376.06,
 451.28,
 488.4,
 524.7,
 511.44,
 700.78,
 537.06,
 601.8,
 440.09999999999997,
 518.28,
 561.26,
 567.0600000000001,
 613.52,
 414.26,
 380.4,
 511.44,
 454.76,
 397.7,
 511.44,
 717.66,
 432.22,
 699.56,
 509.42,
 705.98,
 641.78,
 511.44,
 511.44,
 503.38,
 689.74,
 490.8,
 511.44,
 511.44,
 466.76,
 437.88,
 466.22,
 495.64,
 466.06,
 410.98,
 511.44,
 511.44,
 511.44,
 460.92,
 483.9,
 577.26,
 511.44,
 542.84,
 511.44,
 514.08

In [ ]:
categoria_media = []
for i in media:
  if (i <=200):
    categoria_media.append('E')
  elif (i>200 and i <=400):
    categoria_media.append('D')
  elif (i>400 and i <=600):
    categoria_media.append('C')
  elif (i>600 and i <=800):
    categoria_media.append('B')
  else:
    categoria_media.append('A')
categoria_media

['B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'B'

In [ ]:
dados_pe['CATEGORIA_MEDIA'] = categoria_media

In [ ]:
dados_pe['NU_MEDIA'] = media

In [ ]:
pd.set_option('max_columns', 138)
dados_pe.head()

NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA NO_MUNICIPIO_RESIDENCIA  \
0  190001044305    2019                  2610004                Palmares   
1  190001051159    2019                  2604007                 Carpina   
2  190001058610    2019                  2614105                Sertânia   
3  190001070444    2019                  2610509                 Passira   
4  190001087987    2019                  2610707                Paulista   

   CO_UF_RESIDENCIA SG_UF_RESIDENCIA  NU_IDADE TP_SEXO  TP_ESTADO_CIVIL  \
0                26               PE        21       F                0   
1                26               PE        28       M                1   
2                26               PE        26       M                1   
3                26               PE        33       F                1   
4                26               PE        34       F                1   

   TP_COR_RACA  TP_NACIONALIDADE  CO_MUNICIPIO_NASCIMENTO  \
0            0                 1                2611606.0   
1            2                 1                2608909.0   
2            3                 1                2614105.0   
3            1                 0                      NaN   
4            3                 1                1302603.0   

  NO_MUNICIPIO_NASCIMENTO  CO_UF_NASCIMENTO SG_UF_NASCIMENTO  TP_ST_CONCLUSAO  \
0                  Recife              26.0               PE                1   
1                Limoeiro              26.0               PE                1   
2                Sertânia              26.0               PE                1   
3                     NaN               NaN              NaN                1   
4                  Manaus              13.0               AM                1   

   TP_ANO_CONCLUIU  TP_ESCOLA  TP_ENSINO  IN_TREINEIRO  CO_ESCOLA  \
0                4          1        1.0             0        NaN   
1                6          1        NaN             0        NaN   
2                4          1        NaN             0        NaN   
3               13          1        1.0             0        NaN   
4               13          1        NaN             0        NaN   

   CO_MUNICIPIO_ESC NO_MUNICIPIO_ESC  CO_UF_ESC SG_UF_ESC  \
0               NaN              NaN        NaN       NaN   
1               NaN              NaN        NaN       NaN   
2               NaN              NaN        NaN       NaN   
3               NaN              NaN        NaN       NaN   
4               NaN              NaN        NaN       NaN   

   TP_DEPENDENCIA_ADM_ESC  TP_LOCALIZACAO_ESC  TP_SIT_FUNC_ESC  \
0                     NaN                 NaN              NaN   
1                     NaN                 NaN              NaN   
2                     NaN                 NaN              NaN   
3                     NaN                 NaN              NaN   
4                     NaN                 NaN              NaN   

   IN_BAIXA_VISAO  IN_CEGUEIRA  IN_SURDEZ  IN_DEFICIENCIA_AUDITIVA  \
0               0            0          0                        0   
1               0            0          0                        0   
2               0            0          0                        0   
3               0            0          0                        0   
4               0            0          0                        0   

   IN_SURDO_CEGUEIRA  IN_DEFICIENCIA_FISICA  IN_DEFICIENCIA_MENTAL  \
0                  0                      0                      0   
1                  0                      0                      0   
2                  0                      0                      0   
3                  0                      0                      0   
4                  0                      0                      0   

   IN_DEFICIT_ATENCAO  IN_DISLEXIA  IN_DISCALCULIA  IN_AUTISMO  \
0                   1            0               0           0   
1                   0            0               0           0   
2                   0 

# Verificando a influência dos dados socioeconômicos mais importantes do participante na media das notas.

In [ ]:
# Verificação de dados duplicados
dados_pe[dados_pe.duplicated(['NU_INSCRICAO'],keep=False)]

Empty DataFrame
Columns: [NU_INSCRICAO, NU_ANO, CO_MUNICIPIO_RESIDENCIA, NO_MUNICIPIO_RESIDENCIA, CO_UF_RESIDENCIA, SG_UF_RESIDENCIA, NU_IDADE, TP_SEXO, TP_ESTADO_CIVIL, TP_COR_RACA, TP_NACIONALIDADE, CO_MUNICIPIO_NASCIMENTO, NO_MUNICIPIO_NASCIMENTO, CO_UF_NASCIMENTO, SG_UF_NASCIMENTO, TP_ST_CONCLUSAO, TP_ANO_CONCLUIU, TP_ESCOLA, TP_ENSINO, IN_TREINEIRO, CO_ESCOLA, CO_MUNICIPIO_ESC, NO_MUNICIPIO_ESC, CO_UF_ESC, SG_UF_ESC, TP_DEPENDENCIA_ADM_ESC, TP_LOCALIZACAO_ESC, TP_SIT_FUNC_ESC, IN_BAIXA_VISAO, IN_CEGUEIRA, IN_SURDEZ, IN_DEFICIENCIA_AUDITIVA, IN_SURDO_CEGUEIRA, IN_DEFICIENCIA_FISICA, IN_DEFICIENCIA_MENTAL, IN_DEFICIT_ATENCAO, IN_DISLEXIA, IN_DISCALCULIA, IN_AUTISMO, IN_VISAO_MONOCULAR, IN_OUTRA_DEF, IN_GESTANTE, IN_LACTANTE, IN_IDOSO, IN_ESTUDA_CLASSE_HOSPITALAR, IN_SEM_RECURSO, IN_BRAILLE, IN_AMPLIADA_24, IN_AMPLIADA_18, IN_LEDOR, IN_ACESSO, IN_TRANSCRICAO, IN_LIBRAS, IN_TEMPO_ADICIONAL, IN_LEITURA_LABIAL, IN_MESA_CADEIRA_RODAS, IN_MESA_CADEIRA_SEPARADA, IN_APOIO_PERNA, IN_GUIA_INTERPRETE, IN_COMPUTADOR, IN_CADEIRA_ESPECIAL, IN_CADEIRA_CANHOTO, IN_CADEIRA_ACOLCHOADA, IN_PROVA_DEITADO, IN_MOBILIARIO_OBESO, IN_LAMINA_OVERLAY, IN_PROTETOR_AURICULAR, IN_MEDIDOR_GLICOSE, IN_MAQUINA_BRAILE, IN_SOROBAN, IN_MARCA_PASSO, IN_SONDA, IN_MEDICAMENTOS, IN_SALA_INDIVIDUAL, IN_SALA_ESPECIAL, IN_SALA_ACOMPANHANTE, IN_MOBILIARIO_ESPECIFICO, IN_MATERIAL_ESPECIFICO, IN_NOME_SOCIAL, CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, CO_UF_PROVA, SG_UF_PROVA, TP_PRESENCA_CN, TP_PRESENCA_CH, TP_PRESENCA_LC, TP_PRESENCA_MT, CO_PROVA_CN, CO_PROVA_CH, CO_PROVA_LC, CO_PROVA_MT, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, TX_RESPOSTAS_CN, TX_RESPOSTAS_CH, TX_RESPOSTAS_LC, TX_RESPOSTAS_MT, TP_LINGUA, ...]
Index: []

In [ ]:
dados_pe.columns.get_loc('CATEGORIA_MEDIA')

136

In [ ]:
previsores = dados_pe.iloc[:, 111:136].values
classe = dados_pe.iloc[:, 136].values
classe

array(['B', 'C', 'C', ..., 'C', 'C', 'C'], dtype=object)

In [ ]:
labelencoder = LabelEncoder()
for i in range(4):
  previsores[:,i] = labelencoder.fit_transform(previsores[:, i])
print(previsores[0])

[4 7 5 5 6 'E' 'A' 'D' 'E' 'B' 'A' 'B' 'B' 'B' 'A' 'B' 'A' 'A' 'C' 'A' 'A'
 'E' 'A' 'C' 'B']


In [ ]:
for i in range(5,25):
  previsores[:,i] = labelencoder.fit_transform(previsores[:, i])
print(previsores[0])

[4 7 5 5 6 4 0 3 4 1 0 1 1 1 0 1 0 0 2 0 0 4 0 2 1]


In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores,
                                                        classe,
                                                        test_size = 0.3,
                                                        random_state = 123)

In [ ]:
floresta = RandomForestClassifier(n_estimators=20)
floresta.fit(x_treino,y_treino)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
importancia = floresta.feature_importances_
importancia

array([0.07822687, 0.07388422, 0.06824528, 0.0547651 , 0.10222825,
       0.10408632, 0.01510208, 0.03848317, 0.05572183, 0.03012027,
       0.03099964, 0.01092113, 0.02097971, 0.02620119, 0.01239759,
       0.03369622, 0.00476502, 0.01477204, 0.04084984, 0.03417643,
       0.01744943, 0.06666309, 0.01803242, 0.03356749, 0.01366536])

Podemos observar que os atributos mais importantes se encontram entre Q001 e Q006

In [ ]:
previsao = floresta.predict(x_teste)
acerto = accuracy_score(previsao,y_teste)
acerto

0.8150492523215447

# Previsão utilizando Q001 ao Q006 (Possuíram maior nota do que o teste anterior)

In [ ]:
previsores2 = previsores[:, 0:6]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(previsores2,
                                                    classe,
                                                    test_size = 0.3,
                                                    random_state = 123)

In [ ]:
floresta2 = RandomForestClassifier(n_estimators=20)
floresta2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
previsao2 = floresta2.predict(x_test)
acerto2 = accuracy_score(previsao2,y_test)
acerto2

0.8167666433592169

# Verificando os dados do participante que mais influenciam na predição

In [ ]:
# Recuperando index das features
dados_pe.columns.get_loc('IN_TREINEIRO')

19

In [ ]:
# Tratamento de algumas colunas NaN de dados do participante
moda = int(sts.mode(dados_pe['CO_MUNICIPIO_NASCIMENTO']))
dados_pe['CO_MUNICIPIO_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = sts.mode(dados_pe['NO_MUNICIPIO_NASCIMENTO'])
dados_pe['NO_MUNICIPIO_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = int(sts.mode(dados_pe['CO_UF_NASCIMENTO']))
dados_pe['CO_UF_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = sts.mode(dados_pe['SG_UF_NASCIMENTO'])
dados_pe['SG_UF_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = sts.mode(dados_pe['TP_ENSINO'])
dados_pe['TP_ENSINO'].fillna(moda, inplace=True)

In [ ]:
previsores3 = dados_pe.iloc[:, 2:20].values
previsores3[0]

array([2610004, 'Palmares', 26, 'PE', 21, 'F', 0, 0, 1, 2611606.0,
       'Recife', 26.0, 'PE', 1, 4, 1, 1.0, 0], dtype=object)

In [ ]:
previsores3[:,1] = labelencoder.fit_transform(previsores3[:,1])
previsores3[:,3] = labelencoder.fit_transform(previsores3[:,3])
previsores3[:,5] = labelencoder.fit_transform(previsores3[:,5])
previsores3[:,10] = labelencoder.fit_transform(previsores3[:,10])
previsores3[:,12] = labelencoder.fit_transform(previsores3[:,12])

In [ ]:
previsores3[0]

array([2610004, 113, 26, 0, 21, 0, 0, 0, 1, 2611606.0, 1219, 26.0, 15, 1,
       4, 1, 1.0, 0], dtype=object)

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores3,
                                                        classe,
                                                        test_size = 0.3,
                                                        random_state = 123)

Na célula abaixo iremos verificar a quantidade de valores nulos por atributo.

In [ ]:
pd.set_option('max_rows', 300)
dados_pe.isnull().sum()

NU_INSCRICAO                        0
NU_ANO                              0
CO_MUNICIPIO_RESIDENCIA             0
NO_MUNICIPIO_RESIDENCIA             0
CO_UF_RESIDENCIA                    0
SG_UF_RESIDENCIA                    0
NU_IDADE                            0
TP_SEXO                             0
TP_ESTADO_CIVIL                     0
TP_COR_RACA                         0
TP_NACIONALIDADE                    0
CO_MUNICIPIO_NASCIMENTO             0
NO_MUNICIPIO_NASCIMENTO             0
CO_UF_NASCIMENTO                    0
SG_UF_NASCIMENTO                    0
TP_ST_CONCLUSAO                     0
TP_ANO_CONCLUIU                     0
TP_ESCOLA                           0
TP_ENSINO                           0
IN_TREINEIRO                        0
CO_ESCOLA                      210715
CO_MUNICIPIO_ESC               210715
NO_MUNICIPIO_ESC               210715
CO_UF_ESC                      210715
SG_UF_ESC                      210715
TP_DEPENDENCIA_ADM_ESC         210715
TP_LOCALIZAC

In [ ]:
floresta3 = RandomForestClassifier(n_estimators=20)
floresta3.fit(x_treino,y_treino)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
importancia = floresta3.feature_importances_
importancia

array([0.12421843, 0.12328691, 0.        , 0.        , 0.18622403,
       0.03086206, 0.03633141, 0.09082989, 0.01124731, 0.11250726,
       0.1138231 , 0.01493708, 0.01482373, 0.00681748, 0.08336964,
       0.04543661, 0.00256794, 0.00271712])

agrupamentos

In [ ]:
group_cor_raca = dados_pe.groupby(['TP_COR_RACA']).size()
group_cor_raca

TP_COR_RACA
0      6560
1     77658
2     32396
3    143747
4      7725
5      3641
dtype: int64

In [ ]:
group_no_mun_res = dados_pe.groupby(['NO_MUNICIPIO_RESIDENCIA']).size()
group_no_mun_res

NO_MUNICIPIO_RESIDENCIA
Abreu e Lima                  3268
Afogados da Ingazeira          775
Afrânio                        800
Agrestina                      600
Alagoinha                      379
Aliança                        862
Altinho                        549
Amaraji                        397
Angelim                        237
Araripina                     1719
Araçoiaba                      614
Arcoverde                     2102
Barra de Guabiraba             270
Barreiros                      897
Belo Jardim                   2005
Belém de Maria                 226
Belém do São Francisco         791
Betânia                        217
Bezerros                      1944
Bodocó                         614
Bom Conselho                  1221
Bom Jardim                     980
Bonito                         943
Brejinho                       263
Brejo da Madre de Deus         875
Brejão                         215
Buenos Aires                   333
Buíque                         

In [ ]:
group_no_mun_nas = dados_pe.groupby(['NO_MUNICIPIO_NASCIMENTO']).size()
group_no_mun_nas

NO_MUNICIPIO_NASCIMENTO
Abaetetuba                  5
Abaré                      45
Abreu e Lima             1938
Acajutiba                   1
Acarape                     1
                         ... 
Águas Lindas de Goiás       5
Águas da Prata              1
Águas de Lindóia            2
Águas de São Pedro          2
Álvares Machado             1
Length: 1625, dtype: int64

In [ ]:
group_tp_ano_con = dados_pe.groupby(['TP_ANO_CONCLUIU']).size()
group_tp_ano_con

TP_ANO_CONCLUIU
0     111345
1      34731
2      24037
3      17582
4      13330
5      10790
6       8431
7       7082
8       5755
9       5045
10      4562
11      3478
12      3143
13     22416
dtype: int64

In [ ]:
group_q001 = dados_pe.groupby(['Q001']).size()
group_q001

Q001
A    18247
B    67353
C    39817
D    28640
E    70007
F    15032
G     9183
H    23448
dtype: int64

In [ ]:
group_q005 = dados_pe.groupby(['Q005']).size()
group_q005

Q005
1      5170
2     31880
3     67486
4     90437
5     46993
6     17376
7      7243
8      2986
9      1054
10      613
11      222
12      127
13       59
14       27
15       13
16       13
17        7
18        8
19        1
20       12
dtype: int64

In [ ]:
pd.set_option('max_rows',300)
dados_pe['TP_ENSINO'].isnull().sum()

0