<a href="https://colab.research.google.com/github/andrecarlos26/Projeto-Interdisciplinar-SI-2/blob/main/Sele%C3%A7%C3%A3o_de_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import statistics as sts
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder


caminho = '/content/drive/My Drive/microdados_enem_2019/MICRODADOS_ENEM_2019_PE.csv'
dados_pe = pd.read_csv(caminho)

In [ ]:
dados_pe.head()

NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA NO_MUNICIPIO_RESIDENCIA  \
0  190001044305    2019                  2610004                Palmares   
1  190001051159    2019                  2604007                 Carpina   
2  190001058610    2019                  2614105                Sertânia   
3  190001070444    2019                  2610509                 Passira   
4  190001087987    2019                  2610707                Paulista   

   CO_UF_RESIDENCIA SG_UF_RESIDENCIA  NU_IDADE TP_SEXO  TP_ESTADO_CIVIL  \
0                26               PE        21       F                0   
1                26               PE        28       M                1   
2                26               PE        26       M                1   
3                26               PE        33       F                1   
4                26               PE        34       F                1   

   TP_COR_RACA  TP_NACIONALIDADE  CO_MUNICIPIO_NASCIMENTO  \
0            0                 1                2611606.0   
1            2                 1                2608909.0   
2            3                 1                2614105.0   
3            1                 0                      NaN   
4            3                 1                1302603.0   

  NO_MUNICIPIO_NASCIMENTO  CO_UF_NASCIMENTO SG_UF_NASCIMENTO  TP_ST_CONCLUSAO  \
0                  Recife              26.0               PE                1   
1                Limoeiro              26.0               PE                1   
2                Sertânia              26.0               PE                1   
3                     NaN               NaN              NaN                1   
4                  Manaus              13.0               AM                1   

   TP_ANO_CONCLUIU  TP_ESCOLA  TP_ENSINO  IN_TREINEIRO  CO_ESCOLA  \
0                4          1        1.0             0        NaN   
1                6          1        NaN             0        NaN   
2                4          1        NaN             0        NaN   
3               13          1        1.0             0        NaN   
4               13          1        NaN             0        NaN   

   CO_MUNICIPIO_ESC NO_MUNICIPIO_ESC  CO_UF_ESC SG_UF_ESC  \
0               NaN              NaN        NaN       NaN   
1               NaN              NaN        NaN       NaN   
2               NaN              NaN        NaN       NaN   
3               NaN              NaN        NaN       NaN   
4               NaN              NaN        NaN       NaN   

   TP_DEPENDENCIA_ADM_ESC  TP_LOCALIZACAO_ESC  TP_SIT_FUNC_ESC  \
0                     NaN                 NaN              NaN   
1                     NaN                 NaN              NaN   
2                     NaN                 NaN              NaN   
3                     NaN                 NaN              NaN   
4                     NaN                 NaN              NaN   

   IN_BAIXA_VISAO  IN_CEGUEIRA  IN_SURDEZ  IN_DEFICIENCIA_AUDITIVA  \
0               0            0          0                        0   
1               0            0          0                        0   
2               0            0          0                        0   
3               0            0          0                        0   
4               0            0          0                        0   

   IN_SURDO_CEGUEIRA  IN_DEFICIENCIA_FISICA  IN_DEFICIENCIA_MENTAL  \
0                  0                      0                      0   
1                  0                      0                      0   
2                  0                      0                      0   
3                  0                      0                      0   
4                  0                      0                      0   

   IN_DEFICIT_ATENCAO  IN_DISLEXIA  IN_DISCALCULIA  IN_AUTISMO  \
0                   1            0               0           0   
1                   0            0               0           0   
2                   0 

# Substituição dos valores nulos pela mediana

In [ ]:
# Encontrar index da feature
dados_pe.columns.get_loc('NU_NOTA_REDACAO')

110

In [ ]:
# Criação e inicio de tratamento 
# Nota em Matematica
mediana = dados_pe['NU_NOTA_MT'].median()
dados_pe['NU_NOTA_MT'].fillna(mediana, inplace=True)

In [ ]:
# Ciencias da natureza
mediana = dados_pe['NU_NOTA_CN'].median()
dados_pe['NU_NOTA_CN'].fillna(mediana, inplace=True)

In [ ]:
# Ciencias Humanas
mediana = dados_pe['NU_NOTA_CH'].median()
dados_pe['NU_NOTA_CH'].fillna(mediana, inplace=True)

In [ ]:
# Linguagens e seus códigos
mediana = dados_pe['NU_NOTA_LC'].median()
dados_pe['NU_NOTA_LC'].fillna(mediana, inplace=True)

In [ ]:
mediana = dados_pe['NU_NOTA_REDACAO'].median()
dados_pe['NU_NOTA_REDACAO'].fillna(mediana, inplace=True)

# Criação da coluna Média

In [ ]:
notas = dados_pe.iloc[:,  np.r_[91:95,110]].values
notas

array([[619.6, 674.7, 629.1, 705.7, 880. ],
       [462.2, 499.7, 519.3, 496. , 580. ],
       [462.2, 499.7, 519.3, 496. , 580. ],
       ...,
       [519.4, 513.3, 569.3, 508.5, 700. ],
       [403. , 538.7, 533.9, 395.2, 560. ],
       [499.9, 580.5, 547.5, 478.2, 880. ]])

In [ ]:
media = []

for i in notas:
  media.append(sts.mean(i))
media[:5]

[701.82, 511.44, 511.44, 511.44, 511.44]

In [ ]:
dados_pe['NU_MEDIA'] = media

In [ ]:
# obtenção dos valores dos quantis
quantil_25 = dados_pe['NU_MEDIA'].quantile(0.25)
quantil_50 = dados_pe['NU_MEDIA'].quantile(0.50)
quantil_75 = dados_pe['NU_MEDIA'].quantile(0.75)
print(quantil_25)
print(quantil_50)
print(quantil_75)

470.64
511.44
546.21


In [ ]:
categoria_media = []
for i in media:
  if (i <= quantil_25):
    categoria_media.append('D')
  elif (i > quantil_25 and i <= quantil_50):
    categoria_media.append('C')
  elif (i > quantil_50 and i <= quantil_75):
    categoria_media.append('B')
  else:
    categoria_media.append('A')
categoria_media

['A',
 'C',
 'C',
 'C',
 'C',
 'D',
 'C',
 'A',
 'C',
 'B',
 'C',
 'C',
 'A',
 'A',
 'C',
 'C',
 'B',
 'A',
 'C',
 'A',
 'C',
 'B',
 'A',
 'B',
 'A',
 'A',
 'A',
 'C',
 'C',
 'A',
 'A',
 'A',
 'A',
 'B',
 'A',
 'A',
 'A',
 'D',
 'D',
 'C',
 'A',
 'D',
 'A',
 'A',
 'A',
 'C',
 'C',
 'A',
 'C',
 'C',
 'B',
 'B',
 'B',
 'B',
 'D',
 'A',
 'D',
 'D',
 'C',
 'B',
 'C',
 'A',
 'B',
 'A',
 'D',
 'B',
 'A',
 'A',
 'A',
 'D',
 'D',
 'C',
 'D',
 'D',
 'C',
 'A',
 'D',
 'A',
 'C',
 'A',
 'A',
 'C',
 'C',
 'C',
 'A',
 'C',
 'C',
 'C',
 'D',
 'D',
 'D',
 'C',
 'D',
 'D',
 'C',
 'C',
 'C',
 'D',
 'C',
 'A',
 'C',
 'B',
 'C',
 'B',
 'A',
 'C',
 'A',
 'A',
 'D',
 'B',
 'D',
 'D',
 'D',
 'D',
 'A',
 'A',
 'C',
 'A',
 'C',
 'D',
 'C',
 'A',
 'D',
 'B',
 'A',
 'B',
 'C',
 'A',
 'C',
 'A',
 'A',
 'C',
 'A',
 'C',
 'D',
 'A',
 'D',
 'C',
 'B',
 'D',
 'C',
 'D',
 'A',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'A',
 'C',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'A',
 'A',
 'D',
 'D',
 'B',
 'A',
 'A',
 'A'

In [ ]:
dados_pe['CATEGORIA_MEDIA'] = categoria_media

In [ ]:
dados_pe['NU_MEDIA'] = media

In [ ]:
pd.set_option('max_columns', 138)
dados_pe

NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA NO_MUNICIPIO_RESIDENCIA  \
0       190001044305    2019                  2610004                Palmares   
1       190001051159    2019                  2604007                 Carpina   
2       190001058610    2019                  2614105                Sertânia   
3       190001070444    2019                  2610509                 Passira   
4       190001087987    2019                  2610707                Paulista   
...              ...     ...                      ...                     ...   
271722  190006119912    2019                  2603405                 Calumbi   
271723  190006119913    2019                  2607208                 Ipojuca   
271724  190006119914    2019                  2600104   Afogados da Ingazeira   
271725  190006119915    2019                  2611606                  Recife   
271726  190006119916    2019                  2609600                  Olinda   

        CO_UF_RESIDENCIA SG_UF_RESIDENCIA  NU_IDADE TP_SEXO  TP_ESTADO_CIVIL  \
0                     26               PE        21       F                0   
1                     26               PE        28       M                1   
2                     26               PE        26       M                1   
3                     26               PE        33       F                1   
4                     26               PE        34       F                1   
...                  ...              ...       ...     ...              ...   
271722                26               PE        21       M                1   
271723                26               PE        24       M                1   
271724                26               PE        21       F                2   
271725                26               PE        44       F                1   
271726                26               PE        19       F                1   

        TP_COR_RACA  TP_NACIONALIDADE  CO_MUNICIPIO_NASCIMENTO  \
0                 0                 1                2611606.0   
1                 2                 1                2608909.0   
2                 3                 1                2614105.0   
3                 1                 0                      NaN   
4                 3                 1                1302603.0   
...             ...               ...                      ...   
271722            1                 1                2918407.0   
271723            0                 1                2607208.0   
271724            1                 1                2600104.0   
271725            1                 1                2611606.0   
271726            3                 1                2609600.0   

       NO_MUNICIPIO_NASCIMENTO  CO_UF_NASCIMENTO SG_UF_NASCIMENTO  \
0                       Recife              26.0               PE   
1                     Limoeiro              26.0               PE   
2                     Sertânia              26.0               PE   
3                          NaN               NaN              NaN   
4                       Manaus              13.0               AM   
...                        ...               ...              ...   
271722                Juazeiro              29.0               BA   
271723                 Ipojuca              26.0               PE   
271724   Afogados da Ingazeira              26.0               PE   
271725                  Recife              26.0               PE   
271726                  Olinda              26.0               PE   

        TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  TP_ESCOLA  TP_ENSINO  IN_TREINEIRO  \
0                     1                4          1        1.0             0   
1                     1                6          1        NaN             0   
2                     1                4          1        NaN             0   
3                     1               13          1        1.0             0   
4                     1               13          1 

# Verificando a influência dos dados socioeconômicos mais importantes do participante na media das notas.

In [ ]:
# Verificação de dados duplicados
dados_pe[dados_pe.duplicated(['NU_MEDIA'],keep=False)]

NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA NO_MUNICIPIO_RESIDENCIA  \
0       190001044305    2019                  2610004                Palmares   
1       190001051159    2019                  2604007                 Carpina   
2       190001058610    2019                  2614105                Sertânia   
3       190001070444    2019                  2610509                 Passira   
4       190001087987    2019                  2610707                Paulista   
...              ...     ...                      ...                     ...   
271722  190006119912    2019                  2603405                 Calumbi   
271723  190006119913    2019                  2607208                 Ipojuca   
271724  190006119914    2019                  2600104   Afogados da Ingazeira   
271725  190006119915    2019                  2611606                  Recife   
271726  190006119916    2019                  2609600                  Olinda   

        CO_UF_RESIDENCIA SG_UF_RESIDENCIA  NU_IDADE TP_SEXO  TP_ESTADO_CIVIL  \
0                     26               PE        21       F                0   
1                     26               PE        28       M                1   
2                     26               PE        26       M                1   
3                     26               PE        33       F                1   
4                     26               PE        34       F                1   
...                  ...              ...       ...     ...              ...   
271722                26               PE        21       M                1   
271723                26               PE        24       M                1   
271724                26               PE        21       F                2   
271725                26               PE        44       F                1   
271726                26               PE        19       F                1   

        TP_COR_RACA  TP_NACIONALIDADE  CO_MUNICIPIO_NASCIMENTO  \
0                 0                 1                2611606.0   
1                 2                 1                2608909.0   
2                 3                 1                2614105.0   
3                 1                 0                      NaN   
4                 3                 1                1302603.0   
...             ...               ...                      ...   
271722            1                 1                2918407.0   
271723            0                 1                2607208.0   
271724            1                 1                2600104.0   
271725            1                 1                2611606.0   
271726            3                 1                2609600.0   

       NO_MUNICIPIO_NASCIMENTO  CO_UF_NASCIMENTO SG_UF_NASCIMENTO  \
0                       Recife              26.0               PE   
1                     Limoeiro              26.0               PE   
2                     Sertânia              26.0               PE   
3                          NaN               NaN              NaN   
4                       Manaus              13.0               AM   
...                        ...               ...              ...   
271722                Juazeiro              29.0               BA   
271723                 Ipojuca              26.0               PE   
271724   Afogados da Ingazeira              26.0               PE   
271725                  Recife              26.0               PE   
271726                  Olinda              26.0               PE   

        TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  TP_ESCOLA  TP_ENSINO  IN_TREINEIRO  \
0                     1                4          1        1.0             0   
1                     1                6          1        NaN             0   
2                     1                4          1        NaN             0   
3                     1               13          1        1.0             0   
4                     1               13          1 

In [ ]:
dados_pe.columns.get_loc('CATEGORIA_MEDIA')

137

In [ ]:
previsores = dados_pe.iloc[:, 111:136].values
classe = dados_pe.iloc[:, 137].values
classe

array(['A', 'C', 'C', ..., 'A', 'C', 'A'], dtype=object)

In [ ]:
labelencoder = LabelEncoder()
for i in range(4):
  previsores[:,i] = labelencoder.fit_transform(previsores[:, i])
print(previsores[0])

[4 7 5 5 6 'E' 'A' 'D' 'E' 'B' 'A' 'B' 'B' 'B' 'A' 'B' 'A' 'A' 'C' 'A' 'A'
 'E' 'A' 'C' 'B']


In [ ]:
for i in range(5,25):
  previsores[:,i] = labelencoder.fit_transform(previsores[:, i])
print(previsores[0])

[4 7 5 5 6 4 0 3 4 1 0 1 1 1 0 1 0 0 2 0 0 4 0 2 1]


In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores,
                                                        classe,
                                                        test_size = 0.3,
                                                        random_state = 123)

In [ ]:
floresta = RandomForestClassifier(n_estimators=20)
floresta.fit(x_treino,y_treino)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
importancia = floresta.feature_importances_
importancia

array([0.08818172, 0.07757961, 0.0751893 , 0.06408391, 0.1086081 ,
       0.07888245, 0.00951723, 0.0276725 , 0.06048102, 0.02851245,
       0.03544121, 0.01035931, 0.01932487, 0.03130601, 0.0104177 ,
       0.03747353, 0.00350271, 0.01179596, 0.03854493, 0.03882394,
       0.01570577, 0.06755831, 0.01765882, 0.0257015 , 0.01767716])

Podemos observar que os atributos mais importantes se encontram entre Q001 e Q006

In [ ]:
previsao = floresta.predict(x_teste)
acerto = accuracy_score(previsao,y_teste)
acerto

0.4003115838025491

# Previsão utilizando Q001 ao Q006 (Possuíram maior nota do que o teste anterior)

In [ ]:
previsores2 = previsores[:, 0:6]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(previsores2,
                                                    classe,
                                                    test_size = 0.3,
                                                    random_state = 123)

In [ ]:
floresta2 = RandomForestClassifier(n_estimators=20)
floresta2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
previsao2 = floresta2.predict(x_test)
acerto2 = accuracy_score(previsao2,y_test)
acerto2

0.4078681043683068

# Verificando os dados do participante que mais influenciam na predição

In [ ]:
# Recuperando index das features
dados_pe.columns.get_loc('IN_TREINEIRO')

19

In [ ]:
# Tratamento de algumas colunas NaN de dados do participante
moda = int(sts.mode(dados_pe['CO_MUNICIPIO_NASCIMENTO']))
dados_pe['CO_MUNICIPIO_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = sts.mode(dados_pe['NO_MUNICIPIO_NASCIMENTO'])
dados_pe['NO_MUNICIPIO_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = int(sts.mode(dados_pe['CO_UF_NASCIMENTO']))
dados_pe['CO_UF_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = sts.mode(dados_pe['SG_UF_NASCIMENTO'])
dados_pe['SG_UF_NASCIMENTO'].fillna(moda, inplace=True)

In [ ]:
moda = sts.mode(dados_pe['TP_ENSINO'])
dados_pe['TP_ENSINO'].fillna(moda, inplace=True)

Na célula abaixo iremos verificar a quantidade de valores nulos por atributo.

In [ ]:
pd.set_option('max_rows', 300)
dados_pe.isnull().sum()

NU_INSCRICAO                        0
NU_ANO                              0
CO_MUNICIPIO_RESIDENCIA             0
NO_MUNICIPIO_RESIDENCIA             0
CO_UF_RESIDENCIA                    0
SG_UF_RESIDENCIA                    0
NU_IDADE                            0
TP_SEXO                             0
TP_ESTADO_CIVIL                     0
TP_COR_RACA                         0
TP_NACIONALIDADE                    0
CO_MUNICIPIO_NASCIMENTO             0
NO_MUNICIPIO_NASCIMENTO             0
CO_UF_NASCIMENTO                    0
SG_UF_NASCIMENTO                    0
TP_ST_CONCLUSAO                     0
TP_ANO_CONCLUIU                     0
TP_ESCOLA                           0
TP_ENSINO                           0
IN_TREINEIRO                        0
CO_ESCOLA                      210715
CO_MUNICIPIO_ESC               210715
NO_MUNICIPIO_ESC               210715
CO_UF_ESC                      210715
SG_UF_ESC                      210715
TP_DEPENDENCIA_ADM_ESC         210715
TP_LOCALIZAC

In [ ]:
previsores3 = dados_pe.iloc[:, 2:20].values
previsores3[0]

array([2610004, 'Palmares', 26, 'PE', 21, 'F', 0, 0, 1, 2611606.0,
       'Recife', 26.0, 'PE', 1, 4, 1, 1.0, 0], dtype=object)

In [ ]:
previsores3[:,1] = labelencoder.fit_transform(previsores3[:,1])
previsores3[:,3] = labelencoder.fit_transform(previsores3[:,3])
previsores3[:,5] = labelencoder.fit_transform(previsores3[:,5])
previsores3[:,10] = labelencoder.fit_transform(previsores3[:,10])
previsores3[:,12] = labelencoder.fit_transform(previsores3[:,12])

In [ ]:
previsores3[0]

array([2610004, 113, 26, 0, 21, 0, 0, 0, 1, 2611606.0, 1219, 26.0, 15, 1,
       4, 1, 1.0, 0], dtype=object)

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores3,
                                                        classe,
                                                        test_size = 0.3,
                                                        random_state = 123)

In [ ]:
floresta3 = RandomForestClassifier(n_estimators=20)
floresta3.fit(x_treino,y_treino)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
importancia = floresta3.feature_importances_
importancia

array([0.13725367, 0.13578657, 0.        , 0.        , 0.17808181,
       0.02096609, 0.03623184, 0.08918736, 0.01061111, 0.12253194,
       0.12179706, 0.01318093, 0.01368775, 0.00743255, 0.08105607,
       0.02665109, 0.00259101, 0.00295315])

# Agrupamentos

In [ ]:
group_cor_raca = dados_pe.groupby(['TP_COR_RACA']).size()
group_cor_raca

TP_COR_RACA
0      6560
1     77658
2     32396
3    143747
4      7725
5      3641
dtype: int64

In [ ]:
group_no_mun_res = dados_pe.groupby(['NO_MUNICIPIO_RESIDENCIA']).size()
group_no_mun_res

NO_MUNICIPIO_RESIDENCIA
Abreu e Lima                  3268
Afogados da Ingazeira          775
Afrânio                        800
Agrestina                      600
Alagoinha                      379
Aliança                        862
Altinho                        549
Amaraji                        397
Angelim                        237
Araripina                     1719
Araçoiaba                      614
Arcoverde                     2102
Barra de Guabiraba             270
Barreiros                      897
Belo Jardim                   2005
Belém de Maria                 226
Belém do São Francisco         791
Betânia                        217
Bezerros                      1944
Bodocó                         614
Bom Conselho                  1221
Bom Jardim                     980
Bonito                         943
Brejinho                       263
Brejo da Madre de Deus         875
Brejão                         215
Buenos Aires                   333
Buíque                         

In [ ]:
group_no_mun_nas = dados_pe.groupby(['NO_MUNICIPIO_NASCIMENTO']).size()
group_no_mun_nas

NO_MUNICIPIO_NASCIMENTO
Abaetetuba                  5
Abaré                      45
Abreu e Lima             1938
Acajutiba                   1
Acarape                     1
                         ... 
Águas Lindas de Goiás       5
Águas da Prata              1
Águas de Lindóia            2
Águas de São Pedro          2
Álvares Machado             1
Length: 1625, dtype: int64

In [ ]:
group_tp_ano_con = dados_pe.groupby(['TP_ANO_CONCLUIU']).size()
group_tp_ano_con

TP_ANO_CONCLUIU
0     111345
1      34731
2      24037
3      17582
4      13330
5      10790
6       8431
7       7082
8       5755
9       5045
10      4562
11      3478
12      3143
13     22416
dtype: int64

In [ ]:
group_q001 = dados_pe.groupby(['Q001']).size()
group_q001

Q001
A    18247
B    67353
C    39817
D    28640
E    70007
F    15032
G     9183
H    23448
dtype: int64

In [ ]:
group_q005 = dados_pe.groupby(['Q005']).size()
group_q005

Q005
1      5170
2     31880
3     67486
4     90437
5     46993
6     17376
7      7243
8      2986
9      1054
10      613
11      222
12      127
13       59
14       27
15       13
16       13
17        7
18        8
19        1
20       12
dtype: int64

In [ ]:
pd.set_option('max_rows',300)
dados_pe['TP_ENSINO'].isnull().sum()

0